insert into meeting_comments (id_meeting, id_user, msg) values (23, 'oinchp', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into meeting_comments (id_meeting, id_user, msg) values (7, 'rewensonq', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into meeting_comments (id_meeting, id_user, msg) values (40, 'cbannardh', 'Etiam justo. Etiam pretium iaculis justo.');
insert into meeting_comments (id_meeting, id_user, msg) values (18, 'donioni', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into meeting_comments (id_meeting, id_user, msg) values (39, 'cvasilkovc', 'Etiam pretium iaculis justo.');
insert into meeting_comments (id_meeting, id_user, msg) values (13, 'mmathien', 'Proin risus. Praesent lectus.');
insert into meeting_comments (id_meeting, id_user, msg) values (22, 'mromanet6', 'Integer a nibh. In quis justo.');
insert into meeting_comments (id_meeting, id_user, msg) values (19, 'cpietronir', 'Donec vitae nisi.');
insert into meeting_comments (id_meeting, id_user, msg) values (31, 'aquinbyv', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into meeting_comments (id_meeting, id_user, msg) values (21, 'llurrimanw', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into meeting_comments (id_meeting, id_user, msg) values (30, 'cgorden10', 'In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into meeting_comments (id_meeting, id_user, msg) values (33, 'cgorden10', 'Nunc rhoncus dui vel sem.');
insert into meeting_comments (id_meeting, id_user, msg) values (23, 'bwesley13', 'Integer a nibh.');
insert into meeting_comments (id_meeting, id_user, msg) values (21, 'bwesley13', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into meeting_comments (id_meeting, id_user, msg) values (40, 'bwesley13', 'Cras pellentesque volutpat dui.');
insert into meeting_comments (id_meeting, id_user, msg) values (14, 'bwesley13', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into meeting_comments (id_meeting, id_user, msg) values (3, 'hespinot', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into meeting_comments (id_meeting, id_user, msg) values (35, 'hespinot', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into meeting_comments (id_meeting, id_user, msg) values (29, 'hespinot', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into meeting_comments (id_meeting, id_user, msg) values (30, 'hespinot', 'Duis at velit eu est congue elementum.');
