insert into meeting (id_meeting, admin, date, name, duration) values (1, 'gwife0', '2020-04-30', 'Runolfsson, Rutherford and Schimmel', 2.7);
insert into meeting (id_meeting, admin, date, name, duration) values (2, 'gwife0', '2021-03-02', 'Kuhlman-Nicolas', 3.8);
insert into meeting (id_meeting, admin, date, name, duration) values (3, 'gwife0', '2021-03-23', 'Marvin, Bechtelar and Tremblay', 4.2);
insert into meeting (id_meeting, admin, date, name, duration) values (4, 'chawkeridge1', '2021-01-20', 'Dickens and Sons', 5.0);
insert into meeting (id_meeting, admin, date, name, duration) values (5, 'chawkeridge1', '2020-07-26', 'Runolfsson and Sons', 1.3);
insert into meeting (id_meeting, admin, date, name, duration) values (6, 'chawkeridge1', '2020-09-09', 'Konopelski, McDermott and Runolfsdottir', 6.0);
insert into meeting (id_meeting, admin, date, name, duration) values (7, 'chawkeridge1', '2020-09-29', 'Konopelski, Bradtke and McDermott', 5.8);
insert into meeting (id_meeting, admin, date, name, duration) values (8, 'esimmig2', '2020-06-06', 'Dibbert, Grimes and Weber', 1.4);
insert into meeting (id_meeting, admin, date, name, duration) values (9, 'esimmig2', '2020-09-04', 'Powlowski, Leuschke and Renner', 4.6);
insert into meeting (id_meeting, admin, date, name, duration) values (10, 'esimmig2', '2020-05-24', 'Lang Group', 2.7);
insert into meeting (id_meeting, admin, date, name, duration) values (11, 'llopes3', '2021-04-10', 'Zboncak, Mraz and Crooks', 5.7);
insert into meeting (id_meeting, admin, date, name, duration) values (12, 'llopes3', '2021-01-07', 'Koelpin, Stroman and Berge', 4.8);
insert into meeting (id_meeting, admin, date, name, duration) values (13, 'llopes3', '2021-01-04', 'Rosenbaum, Jast and Hamill', 5.2);
insert into meeting (id_meeting, admin, date, name, duration) values (14, 'adebruijn4', '2021-02-27', 'Jaskolski, Sawayn and Frami', 1.0);
insert into meeting (id_meeting, admin, date, name, duration) values (15, 'adebruijn4', '2020-10-26', 'Padberg-Satterfield', 5.3);
insert into meeting (id_meeting, admin, date, name, duration) values (16, 'adebruijn4', '2020-05-26', 'MacGyver-Tromp', 3.6);
insert into meeting (id_meeting, admin, date, name, duration) values (17, 'adebruijn4', '2020-08-21', 'Lehner, Schinner and Rippin', 3.4);
insert into meeting (id_meeting, admin, date, name, duration) values (18, 'adebruijn4', '2020-09-04', 'Klein, Towne and Cassin', 5.7);
insert into meeting (id_meeting, admin, date, name, duration) values (19, 'kjaquin5', '2020-12-03', 'Rowe-Lockman', 5.9);
insert into meeting (id_meeting, admin, date, name, duration) values (20, 'kmushett6', '2021-03-02', 'Gaylord Group', 1.8);
insert into meeting (id_meeting, admin, date, name, duration) values (21, 'kmushett6', '2020-09-02', 'Romaguera LLC', 2.1);
insert into meeting (id_meeting, admin, date, name, duration) values (22, 'kmushett6', '2020-08-20', 'Jacobson Inc', 5.2);
insert into meeting (id_meeting, admin, date, name, duration) values (23, 'kmushett6', '2020-10-12', 'Mueller, Rippin and Zulauf', 4.0);
insert into meeting (id_meeting, admin, date, name, duration) values (24, 'kmushett6', '2020-07-02', 'Reilly, Wisoky and Halvorson', 2.3);
insert into meeting (id_meeting, admin, date, name, duration) values (25, 'hdifilippo7', '2020-12-09', 'Casper, Schmidt and White', 2.0);
insert into meeting (id_meeting, admin, date, name, duration) values (26, 'hdifilippo7', '2020-11-05', 'Halvorson-Schiller', 5.9);
insert into meeting (id_meeting, admin, date, name, duration) values (27, 'hdifilippo7', '2021-01-14', 'Lindgren, Schoen and Friesen', 2.5);
insert into meeting (id_meeting, admin, date, name, duration) values (28, 'hdifilippo7', '2020-06-18', 'Zemlak Group', 3.9);
insert into meeting (id_meeting, admin, date, name, duration) values (29, 'fagronski8', '2020-09-05', 'Borer, Gusikowski and Brekke', 4.9);
insert into meeting (id_meeting, admin, date, name, duration) values (30, 'rpaff9', '2020-11-25', 'Altenwerth, Jakubowski and Dare', 2.6);
insert into meeting (id_meeting, admin, date, name, duration) values (31, 'rpaff9', '2020-10-12', 'Hauck, Watsica and Ferry', 3.8);
insert into meeting (id_meeting, admin, date, name, duration) values (32, 'rpaff9', '2020-09-09', 'Keeling, McClure and Gibson', 4.4);
insert into meeting (id_meeting, admin, date, name, duration) values (33, 'bkarpushkina', '2020-08-08', 'Becker and Sons', 1.1);
insert into meeting (id_meeting, admin, date, name, duration) values (34, 'bkarpushkina', '2021-03-29', 'Weissnat, Dietrich and Nienow', 4.5);
insert into meeting (id_meeting, admin, date, name, duration) values (35, 'bkarpushkina', '2021-01-08', 'Gleason, Pfannerstill and Grant', 5.8);
insert into meeting (id_meeting, admin, date, name, duration) values (36, 'bkarpushkina', '2020-09-19', 'Towne Inc', 2.8);
insert into meeting (id_meeting, admin, date, name, duration) values (37, 'bkarpushkina', '2020-05-20', 'Cole, Zemlak and Boyle', 5.8);
insert into meeting (id_meeting, admin, date, name, duration) values (38, 'bkarpushkina', '2021-02-20', 'Bergnaum-Runte', 2.1);
insert into meeting (id_meeting, admin, date, name, duration) values (39, 'kjaquin5', '2020-08-24', 'Funk-Kuvalis', 5.6);
insert into meeting (id_meeting, admin, date, name, duration) values (40, 'kjaquin5', '2021-02-05', 'Smith Inc', 3.4);
