insert into user_notification (id_notification, username, msg, viewed) values (1, 'gwife0', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 44);
insert into user_notification (id_notification, username, msg, viewed) values (2, 'gwife0', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 22);
insert into user_notification (id_notification, username, msg, viewed) values (3, 'gwife0', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 14);
insert into user_notification (id_notification, username, msg, viewed) values (4, 'ghuyghe3', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 36);
insert into user_notification (id_notification, username, msg, viewed) values (5, 'chawkeridge1', 'Proin risus.', 42);
insert into user_notification (id_notification, username, msg, viewed) values (6, 'chawkeridge1', 'In blandit ultrices enim.', 44);
insert into user_notification (id_notification, username, msg, viewed) values (7, 'chawkeridge1', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 38);
insert into user_notification (id_notification, username, msg, viewed) values (8, 'esimmig2', 'Aliquam erat volutpat.', 26);
insert into user_notification (id_notification, username, msg, viewed) values (9, 'esimmig2', 'Etiam faucibus cursus urna.', 29);
insert into user_notification (id_notification, username, msg, viewed) values (10, 'llopes3', 'Fusce consequat. Nulla nisl.', 44);
insert into user_notification (id_notification, username, msg, viewed) values (11, 'llopes3', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 39);
insert into user_notification (id_notification, username, msg, viewed) values (12, 'llopes3', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 6);
insert into user_notification (id_notification, username, msg, viewed) values (13, 'adebruijn4', 'Suspendisse potenti.', 2);
insert into user_notification (id_notification, username, msg, viewed) values (14, 'adebruijn4', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 25);
insert into user_notification (id_notification, username, msg, viewed) values (15, 'kjaquin5', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 26);
insert into user_notification (id_notification, username, msg, viewed) values (16, 'kjaquin5', 'Donec semper sapien a libero.', 19);
insert into user_notification (id_notification, username, msg, viewed) values (17, 'kjaquin5', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 33);
insert into user_notification (id_notification, username, msg, viewed) values (18, 'slangstoneb', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 17);
insert into user_notification (id_notification, username, msg, viewed) values (19, 'slangstoneb', 'In sagittis dui vel nisl. Duis ac nibh.', 41);
insert into user_notification (id_notification, username, msg, viewed) values (20, 'slangstoneb', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 21);
